CREATE TABLE IF NOT EXISTS `v2_subscribe_access_logs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int unsigned DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `token_hash` char(64) DEFAULT NULL,
  `subscribe_type` varchar(64) NOT NULL DEFAULT '',
  `flag` varchar(128) DEFAULT NULL,
  `request_host` varchar(255) DEFAULT NULL,
  `request_path` varchar(255) DEFAULT NULL,
  `client_ip` varchar(64) DEFAULT NULL,
  `real_ip_source` varchar(32) DEFAULT NULL,
  `user_agent` text DEFAULT NULL,
  `plan_id` int unsigned DEFAULT NULL,
  `traffic_used` bigint unsigned NOT NULL DEFAULT 0,
  `traffic_total` bigint unsigned NOT NULL DEFAULT 0,
  `expired_at` int DEFAULT NULL,
  `status` tinyint NOT NULL DEFAULT 1,
  `created_at` int NOT NULL,
  `updated_at` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_user_created` (`user_id`, `created_at`),
  KEY `idx_token_created` (`token_hash`, `created_at`),
  KEY `idx_ip_created` (`client_ip`, `created_at`),
  KEY `idx_host_created` (`request_host`, `created_at`),
  KEY `idx_type_created` (`subscribe_type`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
