CREATE TABLE IF NOT EXISTS `v2_subscribe_risk_snapshots` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int unsigned NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `risk_level` varchar(32) NOT NULL DEFAULT '无风险',
  `risk_score` tinyint unsigned NOT NULL DEFAULT 0,
  `original_risk_level` varchar(32) DEFAULT NULL,
  `original_risk_score` tinyint unsigned DEFAULT NULL,
  `disposition_status` varchar(32) NOT NULL DEFAULT 'none',
  `disposition_label` varchar(64) DEFAULT NULL,
  `signals` longtext DEFAULT NULL,
  `metrics` longtext DEFAULT NULL,
  `request_total` int unsigned NOT NULL DEFAULT 0,
  `ip_count` int unsigned NOT NULL DEFAULT 0,
  `host_count` int unsigned NOT NULL DEFAULT 0,
  `agent_count` int unsigned NOT NULL DEFAULT 0,
  `traffic_used` bigint unsigned NOT NULL DEFAULT 0,
  `traffic_total` bigint unsigned NOT NULL DEFAULT 0,
  `first_seen` int DEFAULT NULL,
  `last_seen` int DEFAULT NULL,
  `snapshot_at` int NOT NULL,
  `created_at` int NOT NULL,
  `updated_at` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_user_snapshot` (`user_id`, `snapshot_at`),
  KEY `idx_risk_snapshot` (`risk_level`, `snapshot_at`),
  KEY `idx_disposition_snapshot` (`disposition_status`, `snapshot_at`),
  KEY `idx_snapshot_at` (`snapshot_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
