CREATE TABLE IF NOT EXISTS `v2_subscribe_ip_cache` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `ip` varchar(64) NOT NULL,
  `ip_version` tinyint unsigned NOT NULL DEFAULT 4,
  `country` varchar(64) DEFAULT NULL,
  `region` varchar(128) DEFAULT NULL,
  `city` varchar(128) DEFAULT NULL,
  `isp` varchar(128) DEFAULT NULL,
  `country_code` varchar(16) DEFAULT NULL,
  `asn` int unsigned DEFAULT NULL,
  `as_name` varchar(255) DEFAULT NULL,
  `network_type` varchar(32) DEFAULT NULL,
  `ip_risk_type` varchar(32) DEFAULT NULL,
  `ip_risk_score` tinyint unsigned NOT NULL DEFAULT 0,
  `raw_region` varchar(255) DEFAULT NULL,
  `source` varchar(32) NOT NULL DEFAULT 'ip2region',
  `hit` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` int NOT NULL,
  `updated_at` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_ip` (`ip`),
  KEY `idx_country` (`country`),
  KEY `idx_region` (`region`),
  KEY `idx_isp` (`isp`),
  KEY `idx_asn` (`asn`),
  KEY `idx_network_type` (`network_type`),
  KEY `idx_ip_risk_type` (`ip_risk_type`),
  KEY `idx_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
